### ISSUE TITLE
成绩详情脚本失效

### ISSUE THREAD

**Issue by JessBobby** [lwei02/scu-urp-helpers#1]
应该是换返回地址了。昨天还能看见以下内容和排名，今天就不行了。
![Uploading 无标题.png…]()

**Comment by JessBobby** [comment]
https://www.freeimg.cn/i/2024/01/12/65a1324776aac.png

**Comment by lwei02** [comment]
回调地址没问题，后端返回的数据不正确了，现在后端对这三个数据返回空的字符串，如果后端维持现状就没办法再看这三个数据了
![Screenshot_1](https://github.com/lwei02/scu-urp-helpers/assets/53054067/086e11e1-d3d9-4b97-8605-6954cb78b5ce)

**Comment by JessBobby** [comment]
> 回调地址没问题，后端返回的数据不正确了，现在后端对这三个数据返回空的字符串，如果后端维持现状就没办法再看这三个数据了 ![Screenshot_1](https://private-user-images.githubusercontent.com/53054067/296246059-086e11e1-d3d9-4b97-8605-6954cb78b5ce.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUwNjQ1MDUsIm5iZiI6MTcwNTA2NDIwNSwicGF0aCI6Ii81MzA1NDA2Ny8yOTYyNDYwNTktMDg2ZTExZTEtZDNkOS00Yjk3LTg2MDUtNjk1NGNiNzhiNWNlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTEyVDEyNTY0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc5NDkwMGZhODA2MmIzZWJkNzIyYjk1MWNlMjI4MThiOWE5Y2I2YzQ1NDEyNTcxM2IxZmU0YTNkNDA4ZTIzM2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6uqsXNMJ468r_mo4afiDx5VH7X1XERGR1ZtrBsTKZOo)

感谢！

**Comment by JessBobby** [comment]
> 回调地址没问题，后端返回的数据不正确了，现在后端对这三个数据返回空的字符串，如果后端维持现状就没办法再看这三个数据了 ![Screenshot_1](https://private-user-images.githubusercontent.com/53054067/296246059-086e11e1-d3d9-4b97-8605-6954cb78b5ce.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUwNjQ1MDUsIm5iZiI6MTcwNTA2NDIwNSwicGF0aCI6Ii81MzA1NDA2Ny8yOTYyNDYwNTktMDg2ZTExZTEtZDNkOS00Yjk3LTg2MDUtNjk1NGNiNzhiNWNlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTEyVDEyNTY0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc5NDkwMGZhODA2MmIzZWJkNzIyYjk1MWNlMjI4MThiOWE5Y2I2YzQ1NDEyNTcxM2IxZmU0YTNkNDA4ZTIzM2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6uqsXNMJ468r_mo4afiDx5VH7X1XERGR1ZtrBsTKZOo)

感谢！
